blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('blog/', views.index_page,name='blog'),
    # path('<page_name>/',to_page,name='page'),
    # path('',index_page),
    path('blog_detail/<article_id>/',views.single_blog,name="single_blog"),
    path('create_comment',views.create_comment,name="create_comment"),
    path('json_test' , views.json_test , name="json_test"),
    path('login/' , views.login_page , name="login"),
    path('category/' , views.to_cateogry , name="catetory"),
    path('contact/' , views.to_contact , name="contact"),
    path('404/' , views.to_error , name="error"),
    path('validate_login' , views.validate_login , name="validate_login"),
    path('session_test' , views.session_test , name="session_test"),
    path('logout' , views.logout , name="logout"),
    path('register' , views.reg_page , name="register"),
    path('validate_regemail' , views.validate_regemail , name="validate_regemail"),
    path('validate_username' , views.validate_username , name="validate_username"),
    path('commit_register' , views.commit_register , name="commit_register"),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('__debug__', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/models.py
# -*- conding = utf-8 -*-
from django.db import models
import datetime
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    chinese_name = models.CharField(max_length=100,blank=True,null=True,verbose_name="中文名字")
    img_path = models.CharField(max_length=500,blank=True,null=True,verbose_name="头像路径")
    desc = models.TextField(max_length=100,blank=True,null=True,verbose_name="描述")



class Article(models.Model):
    atc_topic = models.CharField(max_length=100,blank=True,verbose_name="标题")
    atc_desc = models.CharField(max_length=200,blank=True,null=True,verbose_name="描述")
    user = models.ForeignKey(User,blank=True,null=True,on_delete=False,verbose_name="用户")
    atc_content = models.TextField(max_length=2000,null=True,verbose_name="内容")
    click_count = models.IntegerField(null=True,default=0,verbose_name="点击次数")
    like_count = models.IntegerField(blank=True,null=True,default=0,verbose_name="点赞次数")
    create_time = models.DateTimeField(blank=True,null=True,default = datetime.datetime.now(),verbose_name="创建时间")
    update_time = models.DateTimeField(null=True,default = datetime.datetime.now(),verbose_name="更新时间")
    class Meta:
        db_table = 'tbl_article'
        verbose_name = '文章表'
        ordering = ["-id"]


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    atc_id = models.ForeignKey(Article,on_delete=False)
    user = models.ForeignKey(User,null=True,blank=True,on_delete=False)
    cmt_content = models.CharField(max_length=200,null=True)
    create_time = models.DateTimeField(null=True,default = datetime.datetime.now())
    like_count = models.IntegerField(null=True,default=0)
    super_comment = models.IntegerField(null=True,blank=True,default=None)
    username = models.CharField(max_length=30,null=True,blank=True)
    email = models.CharField(max_length=50,null=True,blank=True)
    class Meta:
        db_table = 'tbl_comment'
        verbose_name = '评论表'

class UserTrack(models.Model):
    id = models.AutoField(primary_key=True)
    remote_addr = models.CharField(max_length=100,null=True)
    http_user_agent = models.CharField(max_length=200,null=True)
    http_referer = models.CharField(max_length=200,null=True)
    class Meta:
        db_table = 'tbl_user_track'
        verbose_name = '用户跟踪表'

    @classmethod
    def create(cls, remote_addr,http_user_agent,http_referer):
        track = cls(remote_addr = remote_addr,http_user_agent=http_user_agent,http_referer=http_referer )
        return track

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    cg_name = models.CharField(max_length=50,null=False,verbose_name="分类名称")
    cg_desc = models.TextField(max_length=1000,null=True,blank=True,verbose_name="分类描述")
    imgpath = models.CharField(max_length=500,null=True,blank=True)
    articles = models.ManyToManyField(Article,blank=True)
    class Meta:
        db_table='tbl_category'
        verbose_name = '文章分类'

    def __str__(self):
        return 'Catetory id : ' + str(self.id) + ' Category Name : ' + self.cg_name

# class Mid_atc_cg(models.Model):
#     id = models.AutoField(primary_key=True)
#     atc_id = models.ForeignKey(Article,on_delete=models.CASCADE)
#     cg_id = models.ForeignKey(Category,on_delete=models.CASCADE)
#     class Meta:
#         db_table='tbl_mid_atc_cg'
#         verbose_name = '文章分类中间表'

templates/base_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

	<head>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>{{ title }}</title>



        {% include "base/base_head_css.html" %}
        {% include "base/base-javascript.html" %}
	</head>


	<body>

        <!-- include the top and back button -->
        {% include "base/base_top_and_back.html" %}

        <!-- include the head link section -->
        {% include "base/base_head_section.html" %}

        {% block blog_slider_section %}
            <!-- include the picture under the head section -->

        {% endblock %}


        {% block blog_section %}

                    {% block article_block %}
                        <!-- colm8 -->
                    {% endblock %}

                    {% block side_bar_blank_section %}
                    <!-- all right side bars are included in this html -->

                    {% endblock %}
        {% endblock blog_section %}

        {% block base_footer_block %}
        <!-- Find us section -->
            {% include "base/base_instag_leftram_section.html" %}
            {% include "base/base_footer_section.html" %}

        {% endblock %}
        {% include "base/base_footer_css_section.html" %}

	</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="zxx">

	<head>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Contact</title>

		<!-- css include -->
		<link rel="stylesheet" type="text/css" href="css/materialize.css">
		<link rel="stylesheet" type="text/css" href="css/icofont.css">
		<link rel="stylesheet" type="text/css" href="css/owl.carousel.min.css">
		<link rel="stylesheet" type="text/css" href="css/owl.theme.default.min.css">

		<!-- my css include -->
		<link rel="stylesheet" type="text/css" href="css/custom-menu.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<link rel="stylesheet" type="text/css" href="css/responsive.css">

	</head>


	<body>




		<div class="thetop"></div>
		<!-- for back to top -->

		<div class='backToTop'>
			<a href="#" class='scroll'>
				<span>T</span>
				<span>O</span>
				<span>P</span>
				<span class="go-up">
					<i class="icofont icofont-long-arrow-up"></i>
				</span>
			</a>
		</div>
		<!-- backToTop -->




		<!-- ==================== header-section Start ==================== -->
		<header id="header-section" class="header-section w100dt navbar-fixed">

			<nav class="nav-extended main-nav">
				<div class="container">
					<div class="row">
						<div class="nav-wrapper w100dt">

							<div class="logo left">
								<a href="index.html" class="brand-logo">
									<img src="img/logo.png" alt="brand-logo">
								</a>
							</div>
							<!-- logo -->

							<div>
								<a href="#" data-activates="mobile-demo" class="button-collapse">
									<i class="icofont icofont-navigation-menu"></i>
								</a>
								<ul id="nav-mobile" class="main-menu center-align hide-on-med-and-down">
									<li><a href="index.html">HOME</a></li>
									<li><a href="cateogry.html">CATEGORIES</a></li>
									<li class="dropdown">
										<a href="#">PAGES <i class="icofont icofont-simple-down"></i></a>
										<ul class="dropdown-container">
											<li><a href="404.html">404 Page</a></li>
										</ul>
										<!-- /.dropdown-container -->
									</li>
									<li><a href="single-blog.html">BLOG SINGLE</a></li>
									<li class="active"><a href="contact.html">CONTACT</a></li>
								</ul>
								<!-- /.main-menu -->

								<!-- ******************** sidebar-menu ******************** -->
								<ul class="side-nav" id="mobile-demo">
									<li class="snavlogo center-align"><img src="img/logo.png" alt="logo"></li>
									<li class="active"><a href="index.html">HOME</a></li>
									<li><a href="cateogry.html">CATEGORIES</a></li>
									<li><a href="single-blog.html">SINGLE BLOG</a></li>
									<li><a href="contact.html">CONTACT</a></li>
									<li><a href="404.html">404 PAGE</a></li>
								</ul>
							</div>
							<!-- main-menu -->

							<a href="#" class="search-trigger right">
								<i class="icofont icofont-search"></i>
							</a>
							<!-- search -->
							<div id="myNav" class="overlay">
								<a href="javascript:void(0)" class="closebtn">&times;</a>
								<div class="overlay-content">
									<form>
										<input type="text" name="search" placeholder="Search...">
										<br>
										<button class="waves-effect waves-light" type="submit" name="action">Search</button>
									</form>
								</div>
							</div>

						</div>
						<!-- /.nav-wrapper -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</nav>

		</header>
		<!-- /#header-section -->
		<!-- ==================== header-section End ==================== -->





		<!-- ==================== header-section Start ==================== -->
		<section id="breadcrumb-section" class="breadcrumb-section w100dt mb-30">
			<div class="container">

				<nav class="breadcrumb-nav w100dt">
					<div class="page-name hide-on-small-only left">
						<h4>CONTACT</h4>
					</div>
					<div class="nav-wrapper right">
						<a href="index.html" class="breadcrumb">Home</a>
						<a href="contact.html" class="breadcrumb active">Contact</a>
					</div>
					<!-- /.nav-wrapper -->
				</nav>
				<!-- /.breadcrumb-nav -->

			</div>
			<!-- container -->
		</section>
		<!-- /.breadcrumb-section -->
		<!-- ==================== header-section End ==================== -->





		<!-- ==================== contact-section start ==================== -->
		<section id="contact-section" class="contact-section w100dt mb-50">
			<div class="container">

				<div id="map-section" class="map-section w100dt mb-50">
					<div id="google-map">
						<div id="googleMaps" class="google-map-container"></div>
					</div>
					<!-- /#google-map-->
				</div>
				<!-- /#map-section -->

				<div class="row">
					<div class="col m9 s12">
						<div class="sidebar-title left-align">
							<h2>Contact Me</h2>
						</div>

						<div class="contact-me">
							<div class="row">

								<div class="col m6 s12">
									<p class="mb-30">
										If you have any questions, please contact us through our online support system and we will contact you shortly. Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore.
									</p>

									<div class="contact-things">
										<div class="c-icon">
											<i class="icofont icofont-location-pin"></i>
										</div>
										<div class="c-text p-0">
											<p>452 Town road, Big House</p>
											<p>New York, NY  45896</p>
										</div>
									</div>
									<!-- /.contact-things -->
									<div class="contact-things">
										<div class="c-icon">
											<i class="icofont icofont-phone"></i>
										</div>
										<div class="c-text">
											<p>+88016 8063 6189</p>
										</div>
									</div>
									<!-- /.contact-things -->
									<div class="contact-things">
										<div class="c-icon">
											<i class="icofont icofont-send-mail"></i>
										</div>
										<div class="c-text">
											<p>info@sitename.com</p>
										</div>
									</div>
									<!-- /.contact-things -->
								</div>
								<!-- colsm6 -->

								<div class="col m6 s12">
									<form class="contact-form" action="#">
										<div class="contact-input">
											<input id="first_name" type="text" class="validate">
											<label for="first_name">First Name</label>
										</div>
										<!-- first_name -->

										<div class="contact-input">
											<input id="email" type="email" class="validate">
											<label for="email" data-error="wrong" data-success="right">Email</label>
										</div>
										<!-- email -->

										<div class="contact-input">
											<input id="subject" type="text" class="validate">
											<label for="subject">Subject</label>
										</div>
										<!-- subject -->

										<div class="contact-input">
											<textarea id="textarea1" class="materialize-textarea"></textarea>
											<label for="textarea1">Type your message</label>
										</div>
										<!-- textarea1 -->
										<button type="button" class="waves-effect waves-light right">SEND MESSAGE</button>
									</form>
									<!-- /.contact-form -->
								</div>
								<!-- colsm6 -->

							</div>
							<!-- row -->
						</div>
						<!-- /.contact-me -->
					</div>
					<!-- colm9 -->

					<div class="col m3 s12">
						<div class="sidebar-title left-align">
							<h2>Get Social</h2>
						</div>

						<ul class="social-link">
							<li>
								<a href="#" class="facebook">
									<span class="s-icon left"><i class="icofont icofont-social-facebook"></i></span>
									<span class="s-name">Facebook</span>
									<span class="s-likes right">53K</span>
								</a>
							</li>
							<li>
								<a href="#" class="twitter">
									<span class="s-icon left"><i class="icofont icofont-social-twitter"></i></span>
									<span class="s-name">Twitter</span>
									<span class="s-likes right">652</span>
								</a>
							</li>
							<li>
								<a href="#" class="google-plus">
									<span class="s-icon left"><i class="icofont icofont-social-google-plus"></i></span>
									<span class="s-name">Google+</span>
									<span class="s-likes right">25K</span>
								</a>
							</li>
							<li>
								<a href="#" class="instagram">
									<span class="s-icon left"><i class="icofont icofont-social-instagram"></i></span>
									<span class="s-name">Instagram</span>
									<span class="s-likes right">10K</span>
								</a>
							</li>
							<li>
								<a href="#" class="dribbble">
									<span class="s-icon left"><i class="icofont icofont-social-dribbble"></i></span>
									<span class="s-name">Dribbble</span>
									<span class="s-likes right">543</span>
								</a>
							</li>
						</ul>
					</div>
					<!-- colm3 -->
				</div>
				<!-- row -->

			</div>
			<!-- container -->
		</section>
		<!-- /#contact-section -->
		<!-- ==================== contact-section end ==================== -->





		<!-- ==================== instag leftram-section Start ==================== -->
		<section id="instagram-section" class="instagram-section w100dt">

			<div class="instagram-link w100dt">
				<a href="#">
					<span>FIND US ON INSTAGRAM</span>
					@SUJONMAJIDESIGN
				</a>
			</div>

		</section>
		<!-- /#instag leftram-section -->
		<!-- ==================== instag leftram-section End ==================== -->





		<!-- ==================== footer-section Start ==================== -->
		<footer id="footer-section" class="footer-section w100dt">
			<div class="container">

				<div class="footer-logo w100dt center-align mb-30">
					<a href="#" class="brand-logo">
						<img src="img/logo.png" alt="brand-logo">
					</a>
				</div>
				<!-- /.footer-logo -->

				<ul class="footer-social-links w100dt center-align mb-30">
					<li><a href="#" class="facebook">FACEBOOK</a></li>
					<li><a href="#" class="twitter">TWITTER</a></li>
					<li><a href="#" class="google-plus">GOOGLE+</a></li>
					<li><a href="#" class="linkedin">LINKDIN</a></li>
					<li><a href="#" class="pinterest">PINTEREST</a></li>
					<li><a href="#" class="instagram">INSTAGRAM</a></li>
				</ul>

				<p class="center-align">
					<i class="icofont icofont-heart-alt l-blue"></i>  
					Copyright &copy; 2018.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a>
				</p>

			</div>
			<!-- container -->
		</footer>
		<!-- /#footer-section -->
		<!-- ==================== footer-section End ==================== -->










		<!-- my custom js -->
		<script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>
		<script type="text/javascript" src="js/materialize.js"></script>
		<script type="text/javascript" src="js/owl.carousel.min.js"></script>
		<!-- Google Maps Script  -->
		<script src="http://maps.google.com/maps/api/js?key=AIzaSyC61_QVqt9LAhwFdlQmsNwi5aUJy9B2SyA"></script>
		<script type="text/javascript" src="js/gmap3.min.js"></script>

		<!-- my custom js -->
		<script type="text/javascript" src="js/custom.js"></script>

		<script type="text/javascript">
		
			$(document).ready(function (){
				
				"use strict";
				function isMobile() { 
					return ('ontouchstart' in document.documentElement);
				}

				function init_gmap() {
					if ( typeof google == 'undefined' ) return;
					var options = {
						center: [23.7110734,90.4871938],
						zoom: 14,
						mapTypeControl: true,
						mapTypeControlOptions: {
							style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
						},
						navigationControl: true,
						scrollwheel: false,
						streetViewControl: true,
					}

					if (isMobile()) {
						options.draggable = false;
					}

					$('#google-map').gmap3({
						map: {
							options: options
						},
						marker: {
							latLng: [23.7110734,90.4871938],
							options: { icon: 'img/mark.png' }
						}
					});
				}
				init_gmap();
        /* - Google Map - with support of gmaps.js End 
        --------------------------------------------------------------------*/

    });
</script>


	</body>

</html>

templates/index.html
{% extends "base_blog.html" %}
{% load static %}
{% block blog_slider_section %}
    <!-- include the picture under the head section -->
    {% include "base/base_blog_slider_section.html" %}
    <!-- include the lifestyle section -->
    {% include "base/base_daily_lifestyle.html" %}

{% endblock %}

{% block blog_section %}
<!-- ==================== blog-section start ==================== -->
<section id="blog-section" class="blog-section w100dt mb-50">
    <div class="container">
        <div class="row">
             <div class="col s12 m8 l8">


{% block article_block %}
{% for article in home_article_list %}
    <div class="blogs mb-30">
        <div class="card">
            <div class="card-image">
                <!--<img src="{% static 'img/img3.jpg' %}" alt="Image">-->
                <!--<a class="btn-floating center-align cmn-bgcolor halfway-fab waves-effect waves-light">
                     <i class="icofont icofont-camera-alt"></i>
                </a>-->
            </div>
            <!-- /.card-image -->
            <div class="card-content w100dt">
                <p>
                    <a href="#" class="tag left w100dt l-blue mb-30">Lifestyle</a>
                </p>
                <a href="{% url 'single_blog' article.id %}" class="card-title">
                    {{ article.atc_topic }}
                </a>
                <p class="mb-30">
                    {{ article.atc_desc|slice:"20" }}
                </p>
                <ul class="post-mate-time left">
                    <li>
                        <p class="hero left">
                            By - <a href="#" class="l-blue">SujonMaji</a>
                        </p>
                    </li>
                    <li>
                        <i class="icofont icofont-ui-calendar"></i> {{ article.create_time|date:"Y-m-d H:i:s" }}
                    </li>
                </ul>

                <ul class="post-mate right">
                    <li class="like">
                        <a href="#">
                            <i class="icofont icofont-eye-alt"></i> {{ article.click_count }}
                        </a>
                    </li>
                    <li class="like">
                        <a href="#">
                            <i class="icofont icofont-heart-alt"></i> {{ article.like_count }}
                        </a>
                    </li>
                    <li class="comment">
                        <a href="#">
                            <i class="icofont icofont-comment"></i> {{ article.comment_set.all.count }}
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.card-content -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.blogs -->

{% endfor %}
    <ul class="pagination w100dt">
        {% if home_article_list.has_previous %}
            <li class="active"><a href="?page={{ home_article_list.previous_page_number }}"><i class="icofont icofont-simple-left"></i></a></li>
        {% else %}
            <li class="waves-effect"><a><i class="icofont icofont-simple-left"></i></a></li>
        {% endif %}
        {% if home_article_list.number <= home_article_list.paginator.num_pages %}
{#            <li class="active"><a>{{  home_article_list.number }}</a></li>#}
            {% for i in rangelist %}
                {% if home_article_list.number == i %}
                    <li class="active"><a href="">{{ i }}</a></li>
                {% else %}
                    <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if home_article_list.has_next %}
            <li  class="active"><a href="?page={{ home_article_list.next_page_number }}"><i class="icofont icofont-simple-right"></i></a></li>
        {% else %}
            <li class="waves-effect"><a><i class="icofont icofont-simple-right"></i></a></li>
        {% endif %}
    </ul>
{% endblock %}
</div>

        {% block side_bar_blank_section %}
        <!-- all right side bars are included in this html -->
            {% include "base/base_sidebar_section.html" %}
        {% endblock %}
    </div>
    <!-- row -->
</div>
<!-- container -->
</section>
<!-- /#blog-section -->
<!-- ==================== blog-section end ==================== -->
{% endblock blog_section %}

templates/login.html
{% extends "base_blog.html" %}
{% load static %}
{% block blog_section %}
    <script type="text/javascript">
        function submit_login(){
            $.ajax({
                url:"{% url 'validate_login' %}",
                method:"POST",
                data:{'email':$('#login_email').val(),'password':$('#login_password').val(),'referer_url':$('#referer_url').val()},
                type:"json",
                success:function(callback){
                    var data = $.parseJSON(callback)
                    if (data.lg_flag == 1){
                        window.location.href =data.referer_url
                    }else{
                        alert(data.errormsg)
                    }
                },
            })
        }

    </script>

                <div class="center-in-center" >
                    <div class="center-align">
                        <h2>Login</h2>
                    </div>
                    <form action="{% url "validate_login" %}" method="post" class="comment-area w100dt" id="loginform">
                    {% csrf_token %}
                                <div class="form-item">
                                     {{ lf.email }}
{#                                <label for="login_email">EMAIL</label>#}
                                </div>
                                <br>
                                <div class="form-item">
                               {{ lf.password }}
{#                                 <label for="login_password">PASSWORD</label>#}
                                </div>
                                <input type="hidden" id="referer_url" name="referer_url" value="{{ request.META.HTTP_REFERER }}">
                                <br>
                                <a class="waves-effect waves-light" href="javascript:submit_login()">SUBMIT</a>

                    </form>
                </div>

{% endblock %}
{% block base_footer_block %}
{#    {% include "base/base_footer_section.html" %}#}
{% endblock %}

templates/single-blog.html
{% extends "base_blog.html" %}
{% load static %}
{% block blog_slider_section %}
    {% include "single-blog/base_single_blog_head.html" %}
    <script type="text/javascript">

    </script>
{% endblock %}


{% block blog_section %}

{% block article_block %}
<!-- ==================== single-blog-section start ====================-->
		<section id="single-blog-section" class="single-blog-section w100dt mb-50">
			<div class="container">
				<div class="row">
                 <div class="col m8 s12">
                    <div class="blogs mb-30">
                        <div class="card">

                            <div class="card-image">
                                <img src="{% static 'img/selfie.jpg' %}" alt="Image">
                            </div>
                            <!-- /.card-image -->
                            <div class="card-content w100dt">
                                <p>
                                    <a href="#" class="tag left w100dt l-blue mb-30">Lifestyle</a>
                                </p>
                                <a href="#" class="card-title mb-30">
                                    {{ single_article.atc_topic }}
                                </a>

                                <p class="mb-30">
                                    {{ single_article.atc_desc }}
                                </p>
                                <p>-----------------------------------------------------------</p>

                                <p class="w100dt mb-10">
                                    {{ single_article.atc_content }}
                                </p>


                                <ul class="tag-list left">
                                    {% for category in single_article.category_set.all %}
                                    <li><a href="#!" class="waves-effect">#{{ category.cg_name }}</a></li>
                                    {% endfor %}
                                </ul>
                                <br/><br/>
                                <!--
                                <ul class="share-links right">
                                    <li><a href="#" class="facebook"><i class="icofont icofont-social-facebook"></i></a></li>
                                    <li><a href="#" class="twitter"><i class="icofont icofont-social-twitter"></i></a></li>
                                    <li><a href="#" class="google-plus"><i class="icofont icofont-social-google-plus"></i></a></li>
                                    <li><a href="#" class="linkedin"><i class="icofont icofont-brand-linkedin"></i></a></li>
                                    <li><a href="#" class="pinterest"><i class="icofont icofont-social-pinterest"></i></a></li>
                                    <li><a href="#" class="instagram"><i class="icofont icofont-social-instagram"></i></a></li>
                                </ul>
                                -->
                                 <ul class="post-mate-time left mb-30">
                                    <li>
                                        <p class="hero left">
                                            By - <a href="#" class="l-blue">SujonMaji</a>
                                        </p>
                                    </li>
                                    <li>
                                        <i class="icofont icofont-ui-calendar"></i> {{ single_article.create_time|date:"Y-m-d h:m:s" }}
                                    </li>
                                </ul>

                                <ul class="post-mate right mb-30">
                                    <li class="like" >
                                        <a href="javascript:click_article_like()" >
                                            <i class="icofont icofont-heart-alt"></i> <span id="article_like_count">{{ single_article.like_count }}</span>
                                        </a>
                                    </li>
                                    <li class="comment">
                                        <a href="#">
                                            <i class="icofont icofont-comment"></i> {{ single_article.comment_set.all.count }}
                                        </a>
                                    </li>
                                     <li class="reply">
                                        <a href="javascript:show_leave_comment_div()">
                                            Reply
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- /.card-content -->




                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.blogs -->

    {% include "single-blog/base_previous_next_blog_section.html" %}
    {% include "single-blog/base_blog_comments_section.html" %}
    {% include "single-blog/base_leave_comment_blog_section.html" %}
{% endblock article_block %}
</div>
    {% block side_bar_blank_section %}
    <!-- all right side bars are included in this html -->
        {% include "base/base_sidebar_section.html" %}
    {% endblock %}
    </div>
    <!-- row -->
    </div>
    <!-- container -->
    </section>
{% endblock blog_section %}